# Generated by Django 5.1.7 on 2025-03-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='document_summary',
            field=models.TextField(default=''),
        ),
    ]
